"""add url in post

Revision ID: 0be4d027006b
Revises: 7281c1981902
Create Date: 2021-03-02 19:14:11.842129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be4d027006b'
down_revision = '7281c1981902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'url')
    # ### end Alembic commands ###
