"""init

Revision ID: 50ca16b77b7c
Revises: 
Create Date: 2021-03-09 20:17:37.206806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ca16b77b7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('cardtext', sa.Text(), nullable=True),
    sa.Column('htmltext', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cold', sa.Integer(), nullable=False),
    sa.Column('hot', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicators')
    op.drop_table('posts')
    op.drop_table('owners')
    # ### end Alembic commands ###
