"""empty message

Revision ID: 88d0e71721ee
Revises: 3d082e175950
Create Date: 2020-09-09 22:30:49.522917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d0e71721ee'
down_revision = '3d082e175950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('apartment', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'role')
    op.drop_column('owners', 'apartment')
    # ### end Alembic commands ###
