"""indicators

Revision ID: fa3eb525fe78
Revises: 0be4d027006b
Create Date: 2021-03-04 13:48:50.217808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3eb525fe78'
down_revision = '0be4d027006b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('month', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'month')
    # ### end Alembic commands ###
